use_frameworks!

platform :ios, '8.0'

target 'MrWangLib_Example' do
  pod 'MrWangLib', :path => '../'

  target 'MrWangLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
